const FETCH_WEATHER_ASYNC = 'FETCH_WEATHER_ASYNC';
const SET_SEARCH = 'SET_SEARCH';
const SET_CITY = 'SET_CITY';
const REMOVE_CITY = 'REMOVE_CITY';

export { FETCH_WEATHER_ASYNC, SET_SEARCH, SET_CITY, REMOVE_CITY };
